DocumentRoot /app/frontend

Alias /api /app/backend/api
Alias /includes /app/backend/includes

<Directory /app/backend>
    AllowOverride All
    Require all granted
</Directory>

<Directory /app/frontend>
    AllowOverride All
    Require all granted
</Directory>